In [2]:
pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## The machine learning library in python is installed

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

## Libraries are imported

In [4]:
dd1=pd.read_csv(r"C:\Users\Riaz\Desktop\jupyternotebook\NewCleanedFile.csv")

## Dataset is stored and read.

In [5]:
non_numeric_cols = dd1.select_dtypes(exclude=[np.number]).columns

## Selects columns of non-numeric datatype

In [6]:
label_encoder = LabelEncoder()
dd1_encoded = dd1.copy()

## Instance of label encoder is created and copy of the dataset is created

In [7]:
for col in non_numeric_cols:
    dd1_encoded[col] = label_encoder.fit_transform(dd1[col])

## Iteration starts and the non-numeric columns are transformed to numeric values

In [9]:
X = dd1_encoded.drop(['COMPANY_CLASS'], axis=1)
y = dd1_encoded['COMPANY_CLASS']

## X contains the input feature and y contains the target variable

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Splitting of data into training and testing sets

In [11]:
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

## Initializing RandomForestClassifier

In [12]:
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

## Trains the RandomForestClassifier

In [13]:
y_pred = rf_classifier.predict(X_test)


## Predictions are made on test data


In [14]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)


## Accuracy of the model's prediction 

In [15]:
print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.9373474369406021
Confusion Matrix:
[[13436     0   121]
 [  110    45     0]
 [  693     0   343]]
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.99      0.97     13557
           1       1.00      0.29      0.45       155
           2       0.74      0.33      0.46      1036

    accuracy                           0.94     14748
   macro avg       0.89      0.54      0.62     14748
weighted avg       0.93      0.94      0.93     14748



## Prints the accuracy,confusion matrix,classification report

In [16]:
accuracy_percentage = accuracy * 100

print(f'Accuracy: {accuracy_percentage:.2f}%')

Accuracy: 93.73%


## Calculates accuracy in percentage and prints it